### ISSUE TITLE
Website does not work 

### ISSUE THREAD

**Issue by HeidiSeibold** [davidagraf/doi2bib2#15]
I just tried several different DOIs and always get an error:

![image](https://user-images.githubusercontent.com/14146757/62276798-1b94f200-b445-11e9-91c1-204fc70732ce.png)

My browser: Firefox Quantum 68.0.1 (64-bit)
Let me know if you need any more information.

Thank you so much for the website! I use it a lot for my work :sunflower:

**Comment by davidagraf** [comment]
Hi. Can you please do a hard reload of your browser and try again? Here you see how a hard reload can be done: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.XULMk5MzZ24.

Thanks!

**Comment by HeidiSeibold** [comment]
Works now, thanks!
