### ISSUE TITLE
Unable to find doi from an incomplete URL

### ISSUE THREAD

**Issue by sgrieve** [davidagraf/doi2bib2#2]
I was using the tool today, and copied and pasted the following:

```
doi.org/10.1002/esp.3406
```

into the box on https://www.doi2bib.org and got the message `invalid doi`. I realise that this is technically an invalid doi, and by using either:

```
10.1002/esp.3406
```

or

```
https://doi.org/10.1002/esp.3406
```

a correct result would be obtained. But for users who are not as familiar with the doi specification, who are copying and pasting things from other sites this may lead to confusion. Would it be possible to add a further check to the input string to identify this case, strip `doi.org/` and re-try to get a bibtex file with the corrected string?

Thanks!

**Comment by davidagraf** [comment]
fixed
