### ISSUE TITLE
Get raw Bibtex

### ISSUE THREAD

**Issue by sneumann** [davidagraf/doi2bib2#20]
Hi, it would be great to provide an even simpler http interface
to get just the raw Bibtex. I have several DOIs I want Bibtex'ed, 
`for DOI in X Y Z ; do wget https://www.doi2bib.org/rawbib/$X ; done` 
would be great. 
It think it would be the same as `render()` with the bibtex area only:
https://github.com/davidagraf/doi2bib2/blob/1ff6ea7ee342c8a3505bcb561e0f223ebc029127/client/src/components/Doi2Bib.js#L178
but my JS skills are close to zero. 
Yours, Steffen

**Comment by chrisma** [comment]
Hi Steffen,

the application makes a request to [doi.org](https://www.doi.org/) to fetch the Bibtex entry (see [here](https://github.com/davidagraf/doi2bib2/blob/master/server/doi2bib.js#L7)).

If you're only interested in getting the Bibtex for DOIs (i.e. not arXiv or Pubmed IDs), you can make the request directly from the command line to the same endpoint, e.g.:

`wget --header="Accept: application/x-bibtex" "https://doi.org/10.1073/pnas.242603899"`

**Comment by sneumann** [comment]
Awesome, didn't know that. Thanks, Yours, Steffen
