### ISSUE TITLE
Add `Copy to Clipboard` button

### ISSUE THREAD

**Issue by nnadeau** [davidagraf/doi2bib2#3]
Having a `Copy to Clipboard` button would greatly improve the usability of the web app. :)

**Comment by domoritz** [comment]
I see a copy to cb button now.  

<img width="907" alt="screen shot 2018-08-08 at 10 30 21" src="https://user-images.githubusercontent.com/589034/43853837-19bd2768-9af6-11e8-81a2-d75866833da2.png">

**Comment by thurnherr** [comment]
Yes, we implemented this a couple of weeks ago. Thanks for the suggestion!
