### ISSUE TITLE
Client code usage in Doi2Abstract.org project

### ISSUE THREAD

**Issue by skrzyneckik** [davidagraf/doi2bib2#32]
Hi, inspired by @gvwilson I've started working on doi2abstract website which will provide exactly the same functionality as doi2bib except it will display article's abstract when it's available. As a starting point, I would like to reuse doi2bib2 client code and refer to doi2bib2 as a UI source. Would it be possible?

**Edit**
By looking at doi2bib open issues, I have realised that doi2bib2 doesn't seem to be actively maintained, so I'll wait for a week and if I don't get any response, I'll assume that authors aren't happy about reusing their code.

**Comment by davidagraf** [comment]
Hi @skrzyneckik . Yes, we aren't very active currently. It is absolute ok to reuse our code.

**Comment by skrzyneckik** [comment]
Great! Thanks @davidagraf really appreciate it!
