### ISSUE TITLE
Make month field return integer, not abbreviation

### ISSUE THREAD

**Issue by Benjamin-Lee** [davidagraf/doi2bib2#4]
For example, 
```
@article{Karlin1998,
  doi = {10.1016/s1369-5274(98)80095-7},
  url = {https://doi.org/10.1016/s1369-5274(98)80095-7},
  year  = {1998},
  month = {10},
  publisher = {Elsevier {BV}},
  volume = {1},
  number = {5},
  pages = {598--610},
  author = {Samuel Karlin},
  title = {Global dinucleotide signatures and analysis of genomic heterogeneity},
  journal = {Current Opinion in Microbiology}
}
```

rather than

```
@article{Karlin1998,
  doi = {10.1016/s1369-5274(98)80095-7},
  url = {https://doi.org/10.1016/s1369-5274(98)80095-7},
  year  = {1998},
  month = {oct},
  publisher = {Elsevier {BV}},
  volume = {1},
  number = {5},
  pages = {598--610},
  author = {Samuel Karlin},
  title = {Global dinucleotide signatures and analysis of genomic heterogeneity},
  journal = {Current Opinion in Microbiology}
}
```

During compilation using ShareLaTeX, I get this warning when using the month abbreviation:

`BibTeX month field 'oct' in entry 'Karlin1998' is not an integer - this will probably not sort properly.`

**Comment by axkibe** [comment]
```  month = oct,```
would work fine too. It's just the brackets that are wrong. oct would be a default macro resolving to 10.

**Comment by jowens** [comment]
@axkibe is right (this is the only correct way to do it: `month = oct`). BibTeX has built-in abbreviations for the months (the first three letters of their English month names, all lower case).

FWIW, day-month is `month = "9~" # dec` and month range is `month = aug # "\slash " # sep`.

**Comment by jowens** [comment]
Still interested in seeing this fix.

**Comment by thurnherr** [comment]
By fix, do you mean removing the curly brackets? My concern with numbers is that it is not compatible with natbib/bibtex.

**Comment by axkibe** [comment]
Curly brackets around months are definitely wrong. 
I don't know about natbib. But without brackets it's correct as infact they are only a @string macros to numbers, which breaks if you put brackets around them and messes up sorting.
I don't care if it is replaced with numbers or with names without brackets... both work. Names with brackets don't.

**Comment by davidagraf** [comment]
It's done. The curly brackets around month is gone.
