### ISSUE TITLE
Website Error

### ISSUE THREAD

**Issue by psavery** [davidagraf/doi2bib2#5]
I'm getting an error when I try to use the [website](https://www.doi2bib.org). When I put in the doi and run it, I get this error:

```
The page could not be found

FILE_NOT_FOUND
```

**Comment by psavery** [comment]
By the way, I've been using doi2bib.org for a long time, and the error is new as of today. Maybe it is related to the most recent commit?

**Comment by davidagraf** [comment]
Hi. It works again. Sorry for the inconvenience.
