### ISSUE TITLE
Automatically escape slashes in URI

### ISSUE THREAD

**Issue by timothygebhard** [davidagraf/doi2bib2#6]
When I try to to access the BibTeX entry for a DOI "directly" via the URI, this fails with a "Bad Request" because the slash characters that are part of the DOI are not automatically escaped. 

**Example:**
* This works: [https://doi2bib.org/bib/10.1109%2F5.771073](https://doi2bib.org/bib/10.1109%2F5.771073)
* But this doesn't: [https://doi2bib.org/bib/10.1109/5.771073](https://doi2bib.org/bib/10.1109/5.771073)

It would be pretty neat if scenario 2 also worked, because that would for example allow you to easily set up [doi2bib.org](https://doi2bib.org) as a custom search engine in your browser :)

I _assume_ this should be a rather simple fix (probably just add `encodeURIComponent()` or similar at the right place; perhaps in the `/client/src/components/Doi2bib.js`?), and I'd in principle be happy to try and help with a PR. However, my knowledge about node.js is rather limited and I worry that I will inadvertently break something else…

**Comment by davidagraf** [comment]
@timothygebhard: Can you please check if https://doi2bib-n43nnmtkv.now.sh works for you? The slash is not encoded anymore .... Thanks!

**Comment by timothygebhard** [comment]
@davidagraf This looks great, thank you very much for taking care of this! :)

**Comment by davidagraf** [comment]
doi2big.org is switched to the new version

**Comment by timothygebhard** [comment]
@davidagraf I'm sorry, but I just realized that I might have dismissed the problem too early: Unfortunately, some DOIs contain more than a single slash character, for example: `10.17159/sajs.2017/a0196`. In this case, the current solution still breaks, because everything after the second slash character is discarded when [trying to access the DOI entry directly via the URL](https://www.doi2bib.org/bib/10.17159/sajs.2017/a0196)…

**Comment by davidagraf** [comment]
Oh dear :-(. I will fix it over the weekend.

**Comment by davidagraf** [comment]
@timothygebhard Please check if it works properly now. It's deployed to doi2bib.org directly this time.

**Comment by timothygebhard** [comment]
Looks good to me now! :) Thanks again for taking care of this!
