### ISSUE TITLE
Website error code "Too many requests, please try again later."

### ISSUE THREAD

**Issue by Marius-So** [davidagraf/doi2bib2#80]
The website doi2bib.org is throwing the error "Too many requests, please try again later." for days on all my devices. 

When I build the website myself it works as usual.

**Comment by davidagraf** [comment]
hi. sorry for the troubles. Unfortunately, I am busy today and cannot fix it. Tomorrow, I will fix it.

**Comment by Marius-So** [comment]
No worries just wanted to inform you. Thanks!

**Comment by davidagraf** [comment]
hey. website is working again ...
