### ISSUE TITLE
Website doesn't seem to be working

### ISSUE THREAD

**Issue by SubjunctiveQuaver** [davidagraf/doi2bib2#84]
![image](https://user-images.githubusercontent.com/49895442/188320007-e2d80d69-4553-4cfd-9f29-e82159cdd9db.png)

Hi, I tried using the website today and found that it doesn't seem to work on any of my DOIs. I tried one that I'm almost positive I successfully used in the past, so I think it's an issue with the website, not the DOI.

**Comment by thurnherr** [comment]
Hi there, 

Thanks for getting in touch. I tried your DOI and it worked for me. Not sure why you didn't get any results. Could you try again, please?

![image](https://user-images.githubusercontent.com/7531972/188468059-53bef8b3-8ea3-497f-8f06-fe677bc8a000.png)
