### ISSUE TITLE
Blank screen after entering doi (Firefox)

### ISSUE THREAD

**Issue by gilleslijnzaad** [davidagraf/doi2bib2#85]
I've had this issue for a few months now, making doi2bib unusable on Firefox (version 104.0). I'm on Ubuntu 20.04 LTS.

When I enter a doi and hit `get BibTeX`, the whole screen goes blank. It does not happen when I use Chromium (version 105.0.5195.102).

**Comment by Turakar** [comment]
Same happens here, Fedora 35, recent Firefox version. In the browser console, I can find a 404 for the following XHR request:

`GET https://www.doi2bib.org/2/doi2bib?id=10.1101/2022.07.20.500902`

**Comment by Turakar** [comment]
This seems to be related to CSRF protections regarding www.doi2bib.org vs [doi2bib.org](doi2bib.org). As such, the problem does not appear if you use www.doi2bib.org instead of [doi2bib.org](doi2bib.org).
